protected/controllers/KapalController.php
<?php

class KapalController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array(),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('index','view','exportExcel','admin','delete','create','update',),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array(),
'users'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Kapal;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Kapal']))
{
$model->attributes=$_POST['Kapal'];
if($model->save())
$this->redirect(array('admin'));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Kapal']))
{
$model->attributes=$_POST['Kapal'];
if($model->save())
$this->redirect(array('admin'));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Kapal');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Kapal('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Kapal']))
$model->attributes=$_GET['Kapal'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Kapal::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

  public function actionExportExcel()
	{
			spl_autoload_unregister(array('YiiBase','autoload'));
		
		Yii::import('application.vendors.PHPExcel',true);
		
		spl_autoload_register(array('YiiBase', 'autoload'));

		$PHPExcel = new PHPExcel();
			
		$PHPExcel->getActiveSheet()->setCellValue('A1', 'Laporan Kapal');
		
		$PHPExcel->getActiveSheet()->setCellValue('A3', 'No');
		$PHPExcel->getActiveSheet()->setCellValue('B3', 'Nama Kapal');
		$PHPExcel->getActiveSheet()->setCellValue('C3', 'Tanda Pas');
		$PHPExcel->getActiveSheet()->setCellValue('D3', 'Nama Pemilik');
		$PHPExcel->getActiveSheet()->setCellValue('E3', 'Alamat Pemilik');
		$PHPExcel->getActiveSheet()->setCellValue('F3', 'Npwp Pemilik');
		$PHPExcel->getActiveSheet()->setCellValue('G3', 'Ukuran Panjang');
		$PHPExcel->getActiveSheet()->setCellValue('H3', 'Ukuran Lebar');
		$PHPExcel->getActiveSheet()->setCellValue('I3', 'Ukuran D');
		$PHPExcel->getActiveSheet()->setCellValue('J3', 'Tonase Kotor');
		$PHPExcel->getActiveSheet()->setCellValue('K3', 'Tonase Bersih');
		$PHPExcel->getActiveSheet()->setCellValue('L3', 'Tempat Pembangunan');
		$PHPExcel->getActiveSheet()->setCellValue('M3', 'Tahun Pembangunan');
		$PHPExcel->getActiveSheet()->setCellValue('N3', 'Bahan Utama');
		$PHPExcel->getActiveSheet()->setCellValue('O3', 'Jumlah Geladak');
		$PHPExcel->getActiveSheet()->setCellValue('P3', 'Penggerak');
		$PHPExcel->getActiveSheet()->setCellValue('Q3', 'Mesin Merek');
		$PHPExcel->getActiveSheet()->setCellValue('R3', 'Mesin Daya');
		
		$PHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
			
		$PHPExcel->getActiveSheet()->getStyle('A3:R3')->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);				
		$PHPExcel->getActiveSheet()->getStyle('A3:R3')->getFont()->setBold(true);
		$PHPExcel->getActiveSheet()->getStyle('A3:R3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
		
		$PHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
		$PHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(25);		
		$PHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(35);
		$PHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('M')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('N')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('O')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('P')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('Q')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('R')->setWidth(25);
		
		$i = 1;
		$kolom = 4;

		foreach(Kapal::model()->findAll() as $data)
		{
			$PHPExcel->getActiveSheet()->setCellValue('A'.$kolom, $i);
			$PHPExcel->getActiveSheet()->setCellValue('B'.$kolom, $data->nama_kapal);
			$PHPExcel->getActiveSheet()->setCellValue('C'.$kolom, $data->tanda_pas);
			$PHPExcel->getActiveSheet()->setCellValue('D'.$kolom, $data->nama_pemilik);
			$PHPExcel->getActiveSheet()->setCellValue('E'.$kolom, $data->alamat_pemilik);
			$PHPExcel->getActiveSheet()->setCellValue('F'.$kolom, $data->npwp_pemilik);
			$PHPExcel->getActiveSheet()->setCellValue('G'.$kolom, $data->ukuran_p);
			$PHPExcel->getActiveSheet()->setCellValue('H'.$kolom, $data->ukuran_l);
			$PHPExcel->getActiveSheet()->setCellValue('I'.$kolom, $data->ukuran_d);
			$PHPExcel->getActiveSheet()->setCellValue('J'.$kolom, $data->tonase_kotor);
			$PHPExcel->getActiveSheet()->setCellValue('K'.$kolom, $data->tonase_bersih);
			$PHPExcel->getActiveSheet()->setCellValue('L'.$kolom, $data->tempat_pembangunan);
			$PHPExcel->getActiveSheet()->setCellValue('M'.$kolom, $data->tahun_pembangunan);
			$PHPExcel->getActiveSheet()->setCellValue('N'.$kolom, $data->bahan_utama);
			$PHPExcel->getActiveSheet()->setCellValue('O'.$kolom, $data->jumlah_geladak);
			$PHPExcel->getActiveSheet()->setCellValue('P'.$kolom, $data->penggerak);
			$PHPExcel->getActiveSheet()->setCellValue('Q'.$kolom, $data->mesin_merek);
			$PHPExcel->getActiveSheet()->setCellValue('R'.$kolom, $data->mesin_daya);
										
			$PHPExcel->getActiveSheet()->getStyle('A'.$kolom.':R'.$kolom)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
			
			$i++; $kolom++;
		}
	
		$filename = time().'_LaporanKapal.xlsx';

			$path = Yii::app()->basePath.'/../exports/';
			$objWriter = PHPExcel_IOFactory::createWriter($PHPExcel, 'Excel2007');
			$objWriter->save($path.$filename);	
			$this->redirect(Yii::app()->request->baseUrl.'/exports/'.$filename);

	}



/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='kapal-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('changePassword'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete','create','admin','update'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = CPasswordHelper::hashPassword($model->password);
			if($model->save())
				Yii::app()->user->setFlash('success','User Berhasil ditambahkan');
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = CPasswordHelper::hashPassword($model->password);
			if($model->save())
				Yii::app()->user->setFlash('success','Data Berhasil Diperbarui');
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			Yii::app()->user->setFlash('success','Data Berhasil Dihapus');
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionChangePassword()
	{
		$model = User::model()->findByAttributes(array('username'=>Yii::app()->user->id));

		$ChangePasswordForm = new ChangePasswordForm;

		if(isset($_POST['ChangePasswordForm']))
		{
			
			$model->password = CPasswordHelper::hashPassword($model->password);
			$ChangePasswordForm->attributes = $_POST['ChangePasswordForm'];

			if($ChangePasswordForm->validate())
			{
				$model->password = CPasswordHelper::hashPassword($ChangePasswordForm->password_baru);
				$model->save();
				Yii::app()->user->setFlash('success','Password berhasil diperbarui');
				$this->redirect(array('user/changePassword'));
			}
		}

		$this->render('changePassword',array(
			'model'=>$model,
			'ChangePasswordForm'=>$ChangePasswordForm
		));
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

<div class="row" id="leftMenu" >
	<div class="col-sm-2" >
	<?php $this->widget('booster.widgets.TbMenu',array(
			'type'=>'inverse',
			'htmlOptions' => array('class' => 'left-menu-style'),
			'items' => array(
				array('label' => 'Dashboard','icon'=>'home', 'url' => array('site/index')),
				array('label'=>'Pas Kecil','icon'=>'list', 'url'=>array('/pasKecil/admin')),
				array('label'=>'Export Pas Kecil','icon'=>'download-alt', 'url'=>array('/pasKecil/export')),
				/*array('label'=>'Kapal','icon'=>'plus', 'url'=>array('/kapal/admin')),*/
				array('label'=>'Retribusi','icon'=>'tags', 'url'=>array('/retribusi/admin')),
				array('label'=>'Export Retribusi','icon'=>'download-alt', 'url'=>array('/retribusi/export')),
				array('label'=>'User','icon'=>'user', 'url'=>array('/user/admin'),'visible'=>Yii::app()->user->isAdmin()),
				array('label'=>'Pengaturan','icon'=>'wrench', 'url'=>array('/pengaturan/admin')),
				array('label'=>'Master Data','icon'=>'asterisk', 'items'=>array(
			            	array('label'=>'Jenis Kapal','icon'=>'th-large', 'url'=>array('/jenisKapal/admin')),
			                array('label'=>'Bahan Utama','icon'=>'unchecked','url'=>array('/bahanUtama/admin')),
			                )),
				array('label'=>'Logout ('.Yii::app()->user->name.')','icon'=>'off','url'=>array('site/logout'))
			)
	)); ?>
	</div>


	<div class="col-sm-10">
		<div class="row">
    		<div class="col-sm-12">
    			<div id="breadcumbs">
            		<?php if(isset($this->breadcrumbs)) {
                    	if ( Yii::app()->controller->route !== 'site/index' )

                        $this->breadcrumbs = array_merge(array (Yii::t('zii','<i class="glyphicon glyphicon-home"></i>')=>Yii::app()->homeUrl.'?r=site/index'), $this->breadcrumbs);
                        $this->widget('zii.widgets.CBreadcrumbs', array(
                                'links'=>$this->breadcrumbs,
                                'htmlOptions' => array('class'=>'dim'),
                                'homeLink'=>false,
                                'encodeLabel'=>false,
                                'htmlOptions'=>array ('class'=>'breadcrumb')
                        ));
            		} ?>
            	</div>
            </div>
    	</div>
		<div class="row">
			<div class="col-lg-12 col-md-12">
				<div class="box-content">
				<?php
					foreach(Yii::app()->user->getFlashes() as $key => $message) {
						echo '<div class="alert alert-' . $key . '">';
						echo '<button type="button" class="close" data-dismiss="alert">x</button>';
						print $message;
						print "</div>\n";	
					}
				?>
				</div>
			<?php echo $content; ?>
			</div>
		</div>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/login.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl; ?>/css/login.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div id="content">
	<div class="container">
		<div class="row">
			<div style="width:380px;margin-left:auto;margin-right:auto;margin-top:150px">
			<?php echo $content; ?>
			</div>
			<?php /*
			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">&nbsp;</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">		
					
			</div>
			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">&nbsp;</div>
			*/ ?>
		</div>
	</div>
</div>

</body>
</html>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/admin.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">
	<script src="<?php print Yii::app()->request->baseUrl; ?>/vendors/accounting/accounting.min.js" type="text/javascript"></script>
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="header">
	
		<img class="logo" src="<?php print Yii::app()->baseUrl; ?>/images/logopaskapal.png">
	
</div>

<div id="adminnav">
		<?php $this->widget('booster.widgets.TbNavbar',array(
			'brand' => '',
			'fixed' => false,
			'fluid' => true,
			'type'=>'',
			'items'=>array(
				array(
					'class' => 'booster.widgets.TbMenu',
					'type' => 'navbar',
					'items' => array(
						array('label'=>'Dashboard','icon'=>'home', 'url'=>array('/site/index')),
						array('label' => 'Ganti Password','icon'=>'lock', 'url' => array('user/changePassword')),
						array('label'=>'Masuk', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Keluar ('.Yii::app()->user->name.')','icon'=>'off', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)

						)
					)
			),
		)); ?>
</div><!-- adminnav -->

<div class="containers" id="page">
	<div class="row">
		<div class="col-lg-12">
				<?php echo $content; ?>
		</div>
	</div>
	
	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> Dinas Perhubungan Kabupaten Belitung Timur
	</div><!-- footer -->
</div><!-- page -->
<script>
    $(document).ready(function(){
    
    $(".format-money").on("keyup", function(){
        var _this = $(this);
        var value = _this.val().replace(/\.| /g,"");
        _this.val(accounting.formatMoney(value, "", 0, ".", ","))
    });

});

</script>
</body>
</html>