protected/controllers/KapalController.php
<?php

class KapalController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array(),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('index','view','exportExcel','admin','delete','create','update',),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array(),
'users'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Kapal;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Kapal']))
{
$model->attributes=$_POST['Kapal'];
if($model->save())
$this->redirect(array('admin'));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Kapal']))
{
$model->attributes=$_POST['Kapal'];
if($model->save())
$this->redirect(array('admin'));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Kapal');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Kapal('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Kapal']))
$model->attributes=$_GET['Kapal'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Kapal::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

  public function actionExportExcel()
	{
			spl_autoload_unregister(array('YiiBase','autoload'));
		
		Yii::import('application.vendors.PHPExcel',true);
		
		spl_autoload_register(array('YiiBase', 'autoload'));

		$PHPExcel = new PHPExcel();
			
		$PHPExcel->getActiveSheet()->setCellValue('A1', 'Laporan Kapal');
		
		$PHPExcel->getActiveSheet()->setCellValue('A3', 'No');
		$PHPExcel->getActiveSheet()->setCellValue('B3', 'Nama Kapal');
		$PHPExcel->getActiveSheet()->setCellValue('C3', 'Tanda Pas');
		$PHPExcel->getActiveSheet()->setCellValue('D3', 'Nama Pemilik');
		$PHPExcel->getActiveSheet()->setCellValue('E3', 'Alamat Pemilik');
		$PHPExcel->getActiveSheet()->setCellValue('F3', 'Npwp Pemilik');
		$PHPExcel->getActiveSheet()->setCellValue('G3', 'Ukuran Panjang');
		$PHPExcel->getActiveSheet()->setCellValue('H3', 'Ukuran Lebar');
		$PHPExcel->getActiveSheet()->setCellValue('I3', 'Ukuran D');
		$PHPExcel->getActiveSheet()->setCellValue('J3', 'Tonase Kotor');
		$PHPExcel->getActiveSheet()->setCellValue('K3', 'Tonase Bersih');
		$PHPExcel->getActiveSheet()->setCellValue('L3', 'Tempat Pembangunan');
		$PHPExcel->getActiveSheet()->setCellValue('M3', 'Tahun Pembangunan');
		$PHPExcel->getActiveSheet()->setCellValue('N3', 'Bahan Utama');
		$PHPExcel->getActiveSheet()->setCellValue('O3', 'Jumlah Geladak');
		$PHPExcel->getActiveSheet()->setCellValue('P3', 'Penggerak');
		$PHPExcel->getActiveSheet()->setCellValue('Q3', 'Mesin Merek');
		$PHPExcel->getActiveSheet()->setCellValue('R3', 'Mesin Daya');
		
		$PHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
			
		$PHPExcel->getActiveSheet()->getStyle('A3:R3')->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);				
		$PHPExcel->getActiveSheet()->getStyle('A3:R3')->getFont()->setBold(true);
		$PHPExcel->getActiveSheet()->getStyle('A3:R3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
		
		$PHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
		$PHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(25);		
		$PHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(35);
		$PHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('M')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('N')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('O')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('P')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('Q')->setWidth(25);
		$PHPExcel->getActiveSheet()->getColumnDimension('R')->setWidth(25);
		
		$i = 1;
		$kolom = 4;

		foreach(Kapal::model()->findAll() as $data)
		{
			$PHPExcel->getActiveSheet()->setCellValue('A'.$kolom, $i);
			$PHPExcel->getActiveSheet()->setCellValue('B'.$kolom, $data->nama_kapal);
			$PHPExcel->getActiveSheet()->setCellValue('C'.$kolom, $data->tanda_pas);
			$PHPExcel->getActiveSheet()->setCellValue('D'.$kolom, $data->nama_pemilik);
			$PHPExcel->getActiveSheet()->setCellValue('E'.$kolom, $data->alamat_pemilik);
			$PHPExcel->getActiveSheet()->setCellValue('F'.$kolom, $data->npwp_pemilik);
			$PHPExcel->getActiveSheet()->setCellValue('G'.$kolom, $data->ukuran_p);
			$PHPExcel->getActiveSheet()->setCellValue('H'.$kolom, $data->ukuran_l);
			$PHPExcel->getActiveSheet()->setCellValue('I'.$kolom, $data->ukuran_d);
			$PHPExcel->getActiveSheet()->setCellValue('J'.$kolom, $data->tonase_kotor);
			$PHPExcel->getActiveSheet()->setCellValue('K'.$kolom, $data->tonase_bersih);
			$PHPExcel->getActiveSheet()->setCellValue('L'.$kolom, $data->tempat_pembangunan);
			$PHPExcel->getActiveSheet()->setCellValue('M'.$kolom, $data->tahun_pembangunan);
			$PHPExcel->getActiveSheet()->setCellValue('N'.$kolom, $data->bahan_utama);
			$PHPExcel->getActiveSheet()->setCellValue('O'.$kolom, $data->jumlah_geladak);
			$PHPExcel->getActiveSheet()->setCellValue('P'.$kolom, $data->penggerak);
			$PHPExcel->getActiveSheet()->setCellValue('Q'.$kolom, $data->mesin_merek);
			$PHPExcel->getActiveSheet()->setCellValue('R'.$kolom, $data->mesin_daya);
										
			$PHPExcel->getActiveSheet()->getStyle('A'.$kolom.':R'.$kolom)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
			
			$i++; $kolom++;
		}
	
		$filename = time().'_LaporanKapal.xlsx';

			$path = Yii::app()->basePath.'/../exports/';
			$objWriter = PHPExcel_IOFactory::createWriter($PHPExcel, 'Excel2007');
			$objWriter->save($path.$filename);	
			$this->redirect(Yii::app()->request->baseUrl.'/exports/'.$filename);

	}



/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='kapal-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

	public $layout='//layouts/admin/column2';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		if(Yii::app()->user->isGuest) $this->redirect(array('site/login'));

		$model = new Kapal;

		$this->render('index',array(
			'model'=>$model
		));

	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	public function actionMpdf1($id)
	{
		
		include(Yii::app()->basePath."/vendors/mpdf/mpdf.php");

		$marginLeft = 10;
		$marginRight = 10;
		$marginTop = 10;
		$marginBottom = 20;
		$marginHeader = 5;
		$marginFooter = 5;

		$mpdf = new mPDF('UTF-8','A4',9,'Arial',$marginLeft,$marginRight,$marginTop,$marginBottom,$marginHeader,$marginFooter);

		$model = $this->loadModelKapal($id);
		$kapal = Kapal::model()->findByPk($id);
		

		$html = $this->renderPartial('mpdf1',array('model'=>$model,'kapal'=>$kapal),true);

		$mpdf->WriteHTML($html);

		$mpdf->Output();			
	}

	public function actionMpdf2($id)
	{
		
		include(Yii::app()->basePath."/vendors/mpdf/mpdf.php");

		$marginLeft = 10;
		$marginRight = 10;
		$marginTop = 10;
		$marginBottom = 20;
		$marginHeader = 5;
		$marginFooter = 5;

		$mpdf = new mPDF('UTF-8','A4',9,'Arial',$marginLeft,$marginRight,$marginTop,$marginBottom,$marginHeader,$marginFooter);

		$model = $this->loadModelKapal($id);
		$kapal = Kapal::model()->findByPk($id);
		

		$html = $this->renderPartial('mpdf2',array('model'=>$model,'kapal'=>$kapal),true);

		$mpdf->WriteHTML($html);

		$mpdf->Output();			
	}	

	public function actionMpdf4()
	{
		
		include(Yii::app()->basePath."/vendors/mpdf/mpdf.php");

		$marginLeft = 10;
		$marginRight = 10;
		$marginTop = 10;
		$marginBottom = 20;
		$marginHeader = 5;
		$marginFooter = 5;

		$mpdf = new mPDF('UTF-8','A4',9,'Arial',$marginLeft,$marginRight,$marginTop,$marginBottom,$marginHeader,$marginFooter);

		$html = $this->renderPartial('mpdf4',array(),true);

		$mpdf->WriteHTML($html);

		$mpdf->Output();			
	}		

	/**
	 * Displays the contact page
	 */

	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$this->layout = 'login';
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	public function loadModelKapal($id)
	{
	$model=Kapal::model()->findByPk($id);
	if($model===null)
	throw new CHttpException(404,'The requested page does not exist.');
	return $model;
	}
}

protected/views/kapal/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'kapal-form',
	'type'=>'horizontal',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>
<div class="well">

	<?php echo $form->textFieldGroup($model,'nama_kapal',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
			'widgetOptions'=>array(
				'htmlOptions'=>array()
			)
	)); ?>

	<?php echo $form->textFieldGroup($model,'tanda_pas',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
			'widgetOptions'=>array(
				'htmlOptions'=>array(
					'class'=>'span5',
					'maxlength'=>200)
			)
	)); ?>

	<?php echo $form->textFieldGroup($model,'nama_pemilik',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
			'widgetOptions'=>array(
				'htmlOptions'=>array(
					'class'=>'span5',
					'maxlength'=>255)
			)
	)); ?>

	<?php echo $form->textFieldGroup($model,'alamat_pemilik',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
			'widgetOptions'=>array(
				'htmlOptions'=>array(
					'class'=>'span5',
					'maxlength'=>255)
					)
	)); ?>

	<?php echo $form->textFieldGroup($model,'npwp_pemilik',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>255)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'ukuran_p',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>5)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'ukuran_l',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>5)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'ukuran_d',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>5)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'tonase_kotor',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>5)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'tonase_bersih',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>5)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'tempat_pembangunan',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>255)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'tahun_pembangunan',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>4)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'bahan_utama',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>200)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'jumlah_geladak',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5')
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'penggerak',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array('htmlOptions'=>array(
	'class'=>'span5','maxlength'=>200)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'mesin_merek',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>200)
	)
	)); ?>

	<?php echo $form->textFieldGroup($model,'mesin_daya',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
	'widgetOptions'=>array(
	'htmlOptions'=>array(
	'class'=>'span5',
	'maxlength'=>255)
	)
	)); ?>
</div>
<div>&nbsp;</div>

<div class="form-actions well">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok',
			'label'=>'Simpan',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/kapal/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'nama_kapal',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>200)))); ?>

		<?php echo $form->textFieldGroup($model,'tanda_pas',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>200)))); ?>

		<?php echo $form->textFieldGroup($model,'nama_pemilik',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'alamat_pemilik',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'npwp_pemilik',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'ukuran_p',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>5)))); ?>

		<?php echo $form->textFieldGroup($model,'ukuran_l',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>5)))); ?>

		<?php echo $form->textFieldGroup($model,'ukuran_d',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>5)))); ?>

		<?php echo $form->textFieldGroup($model,'tonase_kotor',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>5)))); ?>

		<?php echo $form->textFieldGroup($model,'tonase_bersih',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>5)))); ?>

		<?php echo $form->textFieldGroup($model,'tempat_pembangunan',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'tahun_pembangunan',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>4)))); ?>

		<?php echo $form->textFieldGroup($model,'bahan_utama',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>200)))); ?>

		<?php echo $form->textFieldGroup($model,'jumlah_geladak',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'penggerak',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>200)))); ?>

		<?php echo $form->textFieldGroup($model,'mesin_merek',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>200)))); ?>

		<?php echo $form->textFieldGroup($model,'mesin_daya',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/kapal/create.php
<?php
$this->breadcrumbs=array(
	'Kapal'=>array('admin'),
	'Tambah',
);

$this->menu=array(
array('label'=>'List Kapal','url'=>array('index')),
array('label'=>'Manage Kapal','url'=>array('admin')),
);
?>

<h1>Tambah Kapal</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/kapal/view.php
<?php
$this->breadcrumbs=array(
	'Kapal'=>array('admin'),
	$model->id,
);
?>

<h1>Tampil Kapal</h1>
<div>&nbsp;</div>
<?php $this->widget('booster.widgets.TbDetailView',array(
		'data'=>$model,
		'type'=>'striped bordered condensed',
		'attributes'=>array(
				'nama_kapal',
				'tanda_pas',
				'nama_pemilik',
				'alamat_pemilik',
				'npwp_pemilik',
				'ukuran_p',
				'ukuran_l',
				'ukuran_d',
				'tonase_kotor',
				'tonase_bersih',
				'tempat_pembangunan',
				'tahun_pembangunan',
				'bahan_utama',
				'jumlah_geladak',
				'penggerak',
				'mesin_merek',
				'mesin_daya',
		),
)); ?>

<div>&nbsp;</div>
<div class="well">
	<?php $this->widget('booster.widgets.TbButton', array(
		'buttonType'=>'link',
		'url'=>array('update','id'=>$model->id),
		'context'=>'primary',
		'icon'=>'pencil',
		'label'=>'Sunting',
		'htmlOptions'=>array('class'=>'dim')
	)); ?>&nbsp;
	
	 <?php 
		$this->widget('booster.widgets.TbButton', array(
					'buttonType'=>'link',
					'context'=>'success',
					'icon'=>'print',
					'url'=>array('pasKecil/registerPasKecilPdf','id'=>$model->id),
					'label'=>'Cetak Register Pas Kecil',
					'htmlOptions'=>array('target'=>'_blank'),
			));
	 ?>
	 <?php 
		$this->widget('booster.widgets.TbButton', array(
					'buttonType'=>'link',
					'context'=>'success',
					'icon'=>'print',
					'url'=>array('site/mpdf4','id'=>$model->id),
					'label'=>'Cetak Daftar Ukur Dalam Negeri',
					'htmlOptions'=>array('target'=>'_blank'),
			));
	 ?>
</div>